server.port=8080

spring.application.name=elevators-application

spring.datasource.url=mysql://avnadmin:AVNS_Eot1PI5Va60oq8nNYs-@mysql-39ca64a-chautrieu3112-6cf3.h.aivencloud.com:17016/defaultdb?ssl-mode=REQUIRED

spring.datasource.username=avnadmin
spring.datasource.password=AVNS_Eot1PI5Va60oq8nNYs-

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect